[package]
name = "shokomusic-finder-rs"
version = "0.1.1"
edition = "2024"

[dependencies]
urlencoding = "2.1.3"
reqwest = { version = "0.13.2", features = ["blocking", "json"]}
serde_json = "1.0.149"
